name: Record RTSP Stream to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Record RTSP stream
      run: |
        ffmpeg -i rtsp://AnsumanBehera:Anshu2024@192.168.29.157:554/stream1 -c:v copy -t 3600 output/recorded_stream.mp4

    - name: Install Google Drive API Client
      run: |
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Upload to Google Drive
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}  # Using the secret for Client ID
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}  # Using the secret for Client Secret
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}  # Using the secret for Refresh Token
      run: |
        echo "import os
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        # Authenticate and create the service
        creds = Credentials(
            None,
            refresh_token=os.getenv('GOOGLE_REFRESH_TOKEN'),
            client_id=os.getenv('GOOGLE_CLIENT_ID'),
            client_secret=os.getenv('GOOGLE_CLIENT_SECRET'),
            token_uri='https://oauth2.googleapis.com/token',
        )
        drive_service = build('drive', 'v3', credentials=creds)

        # Create file metadata
        file_metadata = {'name': 'recorded_stream.mp4', 'parents': ['15Kp8uCiK65E_r_Rp3T92SmUZkLfddDCZ']}
        media = MediaFileUpload('output/recorded_stream.mp4', mimetype='video/mp4')

        # Upload the file
        file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()
        print('File ID: %s' % file.get('id'))" > upload_to_drive.py
        python upload_to_drive.py
